import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# --- 1. SETTINGS & STYLING ---
st.set_page_config(page_title="Survey Insights", layout="wide")
sns.set_style("whitegrid")

# Custom CSS for better UI
st.markdown("""
    <style>
    .main { background-color: #f9f9f9; }
    .stMetric { border: 1px solid #e6e6e6; padding: 10px; border-radius: 5px; }
    </style>
    """, unsafe_allow_html=True)

# --- 2. DATA PROCESSING LAYER ---
@st.cache_data
def load_and_clean_data():
    # Replace with: df = pd.read_csv("your_file.csv")
    # For now, using simulated data
    q_cols = [
        'follow_for_updates_promotions', 'follow_because_like_products',
        'follow_because_entertaining', 'follow_because_discounts_contests',
        'follow_because_express_personality', 'follow_because_online_community',
        'follow_because_support_loyalty'
    ]
    data = np.random.randint(1, 6, size=(250, len(q_cols)))
    df = pd.DataFrame(data, columns=q_cols)
    df['Gender'] = np.random.choice(['Male', 'Female', 'Other'], size=250)
    df['Gender'] = df['Gender'].astype(str).str.strip()
    return df, q_cols

df, motivation_questions = load_and_clean_data()

# --- 3. HEADER & SUMMARY METRICS ---
st.title("📊 Motivation Analysis Dashboard")
st.caption("Analyzing consumer behavior and brand engagement motivations.")

# High-level metrics for quick glance
m1, m2, m3 = st.columns(3)
with m1:
    st.metric("Total Responses", len(df))
with m2:
    top_motivation = df[motivation_questions].mean().idxmax().replace('_', ' ').title()
    st.metric("Primary Driver", top_motivation)
with m3:
    st.metric("Confidence Level", "95%")

st.divider()

# --- 4. INTERACTIVE FILTER LAYER ---
with st.sidebar:
    st.header("⚙️ Configuration")
    genders = df['Gender'].unique().tolist()
    selected_genders = st.multiselect("Filter by Gender", options=genders, default=genders)
    
    st.markdown("---")
    st.info("The charts on the right update automatically based on your selection.")

# Filtered dataset
filtered_df = df[df['Gender'].isin(selected_genders)]

# --- 5. VISUALIZATION LAYER ---
tab1, tab2, tab3 = st.tabs(["📈 Performance Scores", "🔗 Relationship Analysis", "👥 Demographic Split"])

# TAB 1: OVERALL PERFORMANCE
with tab1:
    col_a, col_b = st.columns([1, 1])
    
    with col_a:
        st.subheader("Mean Agreement")
        means = filtered_df[motivation_questions].mean().sort_values(ascending=False)
        fig1, ax1 = plt.subplots(figsize=(8, 6))
        sns.barplot(x=means.values, y=means.index, palette='viridis', ax=ax1)
        ax1.set_xlim(0, 5)
        for i, v in enumerate(means.values):
            ax1.text(v + 0.05, i, f'{v:.2f}', va='center', fontweight='bold')
        st.pyplot(fig1)

    with col_b:
        st.subheader("Response Distribution")
        dist_data = []
        for q in motivation_questions:
            counts = filtered_df[q].value_counts(normalize=True).reindex(range(1, 6), fill_value=0) * 100
            dist_data.append(counts.values)
        
        df_pct = pd.DataFrame(dist_data, index=motivation_questions, 
                             columns=['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'])
        
        fig2, ax2 = plt.subplots(figsize=(8, 6))
        colors = ["#d73027", "#fc8d59", "#ffffbf", "#91cf60", "#1a9850"]
        df_pct.plot(kind='barh', stacked=True, color=colors, ax=ax2)
        ax2.legend(bbox_to_anchor=(1, 1))
        st.pyplot(fig2)

# TAB 2: CORRELATIONS
with tab2:
    st.subheader("Correlation Heatmap")
    corr = filtered_df[motivation_questions].corr()
    fig3, ax3 = plt.subplots(figsize=(10, 6))
    sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", ax=ax3)
    st.pyplot(fig3)

# TAB 3: GENDER ANALYSIS
with tab3:
    st.subheader("Gender Comparison (Dumbbell Plot)")
    if len(selected_genders) < 2:
        st.warning("Please select at least two gender categories in the sidebar to compare differences.")
    else:
        g_means = filtered_df.groupby('Gender')[motivation_questions].mean().T
        g_melted = g_means.reset_index().melt(id_vars='index', var_name='Gender', value_name='Score')
        
        fig4, ax4 = plt.subplots(figsize=(10, 7))
        sns.pointplot(data=g_melted, x='Score', y='index', hue='Gender', join=True, markers='o', scale=1.1, ax=ax4)
        ax4.set_xlim(1, 5)
        st.pyplot(fig4)

# --- 6. FOOTER ---
st.markdown("---")
st.caption("Dashboard generated by Gemini. Data source: Respondent CSV.")
